### ISSUE TITLE
Prometheus exporters

### ISSUE THREAD

**Issue by robcxyz** [sb-icon/icon-etl#17]
Setup prom exporter with the following attributes:

- No flag to configure ports -> Fix at 9401? or anything that makes sense.  Doesn't need configuration to make it simpler

Labels on each metric
- network_name
- container_name -> Should come through as env var or something that grabs the serviceName?
```
  serviceName: {{ include "statefulsetName" . }}
```

Metrics 
- block_height_start -> Saved from init? Only issue is if container restarts which is of little worry. 
- block_height
- Anything else super obvious and needed? Don't think so?

**Comment by shinyfoil** [comment]
Added to forked bx-common package  (now being pushed to pypi as blockchain-etl-common-instrumented):

- start_block
- end_block
- target_block
- last_synced_block

Need to figure out what makes sense for network_name and container_name.

network_name would have to be set separately since we only really interact with things through the "provider_uri" var.
container_name could be provided through an env var via the downward api (probably?)

This would probably end up having to be pushed up into the upstream common package so that they're applied as labels though...
